[build.environment]
  YARN_VERSION = "1.22.19"
  NPM_VERSION = "8.11.0"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:preview"
